seed_everything: 123
trainer:
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "lstm_vae"
      save_dir: "./wandb/lstm_vae"
      log_model: "all"
  max_epochs: 1000
  default_root_dir: ./lightning_logs/lstm_vae
model:
  class_path: models.LSTM_VAE
  init_args:
    feature: 1886
    hidden_size: 256
    dim_encoded: 128
    num_layers: 2
    num_classes: 2
    vae_ckpt_path: 'pretrained_ckpts/vae.ckpt'
data:
  class_path: datasets.CallRecordsDataModule
  init_args:
    data_dir: './data'
    batch_size: 32
    seed: 12
    non_seq: false
    num_workers: 4