# lightning.pytorch==2.3.1
seed_everything: 123
trainer:
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "lstm"
      save_dir: "./wandb/lstm"
      log_model: "all"
  max_epochs: 100
  default_root_dir: ./lightning_logs/lstm
model:
  class_path: models.LSTM
  init_args:
    input_size: 1886
    hidden_size: 128
    num_layers: 2
    num_classes: 2
data:
  class_path: datasets.CallRecordsDataModule
  init_args:
    data_dir: './data'
    batch_size: 32
    seed: 12
    non_seq: false
    num_workers: 1