seed_everything: 123
trainer:
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "vae"
      save_dir: "./wandb/vae"
      log_model: "all"
  max_epochs: 1000
  default_root_dir: ./lightning_logs/vae
model:
  class_path: models.VAE
  init_args:
    in_channels: 2062
    latent_dim: 128
data:
  class_path: datasets.CallRecords4VAEDataModule
  init_args:
    data_dir: './data'
    batch_size: 512
    seed: 12
    num_workers: 4