# lightning.pytorch==2.3.1
seed_everything: 123
trainer:
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "vae"
      save_dir: "./wandb/${trainer.logger.init_args.project}"
      log_model: "all"
  max_epochs: 1000
  default_root_dir: "./lightning_logs/${trainer.logger.init_args.project}"
model:
  class_path: models.VAE
  init_args:
    in_channels: 1902
    latent_dim: 128
data:
  class_path: datasets.CallRecords4VAEDataModule
  init_args:
    data_dir: "./data"
    batch_size: 4096
    seed: 12
    num_workers: 8
