# lightning.pytorch==2.3.1
seed_everything: 123
ckpt_path: null
trainer:
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "xlstm"
      save_dir: "./wandb/${trainer.logger.init_args.project}"
      log_model: true
  max_epochs: 100
  default_root_dir: ./lightning_logs/${trainer.logger.init_args.project}
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "valid_BinaryF1Score"
        mode: "max"
        save_top_k: 10
        filename: "{epoch}-{valid_BinaryF1Score:.3f}"
        verbose: false
    - class_path: callbacks.LSTMPredictionWriter
      init_args:
        output_dir: "./predictions/${trainer.logger.init_args.project}"
        write_interval: "epoch"
model:
  class_path: models.xLSTM
  init_args:
    input_size: 1902
    head_size: 128
    head_num: 4
    num_layers: 4
    signature: [3, 1]
    num_classes: 2
    p_factor: [2, 1.33333]
    ker_size: 4
data:
  class_path: datasets.CallRecordsDataModule
  init_args:
    data_dir: "./data"
    batch_size: 16
    seed: 12
    non_seq: false
    num_workers: 1
